services:
  frontend:
    container_name: frontend
    build:
      dockerfile: Dockerfile
      # Use development stage for hot-reload
      target: build
    ports:
      - "3000:5173"  # Thay đổi cổng 80 thành 3000 để tránh xung đột
    volumes:
      # Mount source code for development
      - ./:/app
      # Exclude node_modules
      - /app/node_modules
    command: npm run dev -- --host 0.0.0.0 --force
    restart: always
    networks:
      - backend_default
    environment:
      - VITE_API_BASE_URL=http://localhost:8000/api/v1

# default network backend
networks:
  backend_default:
    external: true