version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - BACKEND_CORS_ORIGINS=["*"]
      - AI_PROVIDER=gemini
    volumes:
      - ./backend/.env:/app/.env
      # Mount source code for development
      - ./backend:/app
    command: python -m uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    restart: always
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      # Use development stage for hot-reload
      target: build
    ports:
      - "80:5173"
    volumes:
      # Mount source code for development
      - ./frontend:/app
      # Exclude node_modules
      - /app/node_modules
    command: npm run dev -- --host 0.0.0.0
    depends_on:
      - backend
    restart: always
    environment:
      - VITE_API_BASE_URL=http://backend:8000/api/v1
    networks:
      - app-network

networks:
  app-network:
    driver: bridge