services:
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - BACKEND_CORS_ORIGINS=["*"]
      - AI_PROVIDER=gemini
    volumes:
      - ./backend/.env:/app/.env
      # Mount source code for development
      - ./backend:/app
    command: python -m uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    restart: always

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
      # Use development stage for hot-reload
      target: build
    ports:
      - "80:5173"
    volumes:
      # Mount source code for development
      - ./frontend:/app
      # Exclude node_modules
      - /app/node_modules
    command: npm run dev -- --host 0.0.0.0
    depends_on:
      - backend
    restart: always
    environment:
      - VITE_API_BASE_URL=http://backend:8000/api/v1

  mcp-server:
    container_name: mcp-server
    build:
      context: ./mcpserver
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    volumes:
      - ./mcpserver:/app  # Correctly mount the mcpserver directory