services:
  mysql:
    container_name: mysql
    image: mysql:8.0
    ports:
      - "3308:3306"
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: proagents
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 10
      interval: 5s

  backend:
    container_name: backend
    environment:
      - TZ=Asia/Ho_Chi_Minh
    build:
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
      - ./.env:/app/.env
    command: python /app/run.py --host
    restart: always
    depends_on:
      mysql:
        condition: service_healthy

volumes:
  mysql_data: