services:
  mysql:
    container_name: mysql
    image: mysql:8.0
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: proagents
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 10
      interval: 5s

  backend:
    container_name: backend
    build:
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - BACKEND_CORS_ORIGINS=["*"]
      - AI_PROVIDER=gemini
      - SQL_DB_URL=mysql+pymysql://root:123@mysql:3306/proagents
      - JWT_SECRET_KEY=${JWT_SECRET_KEY:-your_super_secret_key_for_jwt_tokens}
    volumes:
      - ./:/app
      - ./.env:/app/.env
    command: python /app/run.py 
    restart: always
    depends_on:
      mysql:
        condition: service_healthy

volumes:
  mysql_data: